project_id = "lpfzrsdqyqesjzfaxqwq"

[functions.bunny-upload]
verify_jwt = false

[functions.bunny-delete]
verify_jwt = false

[functions.create-branch-staff]
verify_jwt = false

[functions.delete-branch-staff]
verify_jwt = false

[functions.create-payment-session]
verify_jwt = false

[functions.kashier-webhook]
verify_jwt = false

[functions.auto-renew-subscriptions]
verify_jwt = false
