// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpfzrsdqyqesjzfaxqwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwZnpyc2RxeXFlc2p6ZmF4cXdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NTA0MzksImV4cCI6MjA4NjIyNjQzOX0.GYZpV-ZRdFGOfCS1BcIb4d4DoZBaCvgW-ndv55WRXS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});